### ISSUE TITLE
How to play audio in the background or when screen if off?

### ISSUE THREAD

**Issue by gmg2719** [Dsiner/CommenPlayer#13]
How to play audio in the background or when screen if off?
Most of the popular video player support this feature.  I want to know how it is implemented.

**Comment by Dsiner** [comment]
@gmg2719 
https://developer.android.google.cn/about/versions/oreo/background

https://developer.android.google.cn/guide/components/foreground-services

**Comment by gmg2719** [comment]
Thanks a lot!
