### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [Dsiner/CommenPlayer#6]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by Dsiner** [comment]
@anharismail Yes! You can do as you want. Thanks you in advance!

**Comment by anharismail** [comment]
Hello @Dsiner, this is my logo proposal for your project. This logo was inspired by player element and 'C' initial. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

I'll provide all file types and sizes you needed.

Hope you like it :)

![commenplayer ver 1](https://user-images.githubusercontent.com/37614260/43684605-5f3f8978-98cd-11e8-8211-1a903c8faa22.png)

**Comment by Dsiner** [comment]
@anharismail Great, I like it at first sight. Thank you!

**Comment by Dsiner** [comment]
@anharismail I don't think I have any other better suggestions because it is so beautiful.

**Comment by anharismail** [comment]
Great, thanks for your appreciation @dsiner. Will you use it on your project?

Can I pull a request to put it on your readme and repository?

**Comment by Dsiner** [comment]
Sure.

**Comment by Dsiner** [comment]
@anharismail Sure.

**Comment by anharismail** [comment]
Hi @Dsiner , I've just posted a folder on your repository. I'll wait until the logo used on your project :)

**Comment by Dsiner** [comment]
@anharismail The logo has been replaced. It looks cool. Thank you again.

**Comment by anharismail** [comment]
Hi @Dsiner, that was great. Very happy to see your positive and fast response.

Please ask me again, if you need another logo for your other project :)

**Comment by Dsiner** [comment]
@anharismail 
Oh, sorry, I missed it.
You are very kind. I am sure that I don't need another logo for another project, and thank you again.
