### ISSUE TITLE
Hey. Help to understand. How to increase the buffer for live video

### ISSUE THREAD

**Issue by Bulikc** [Dsiner/CommenPlayer#8]
video streaming freezes. And rare are artefatti

**Comment by Dsiner** [comment]
@Bulikc 
Try this https://github.com/danikula/AndroidVideoCache

**Comment by Bulikc** [comment]
Hello, if I have a landscape orientation does not work full screen. How to code set Fullscreen?

**Comment by Dsiner** [comment]
@Bulikc 
Refer to https://github.com/Dsiner/CommenPlayer/issues/2
